# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(330, 335)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dirPath = QtWidgets.QLineEdit(self.centralwidget)
        self.dirPath.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.dirPath.setObjectName("dirPath")
        self.horizontalLayout.addWidget(self.dirPath)
        self.setPath = QtWidgets.QToolButton(self.centralwidget)
        self.setPath.setObjectName("setPath")
        self.horizontalLayout.addWidget(self.setPath)
        self.dtnStart = QtWidgets.QPushButton(self.centralwidget)
        self.dtnStart.setMinimumSize(QtCore.QSize(0, 0))
        self.dtnStart.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dtnStart.setObjectName("dtnStart")
        self.horizontalLayout.addWidget(self.dtnStart)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.result = QtWidgets.QTextBrowser(self.centralwidget)
        self.result.setObjectName("result")
        self.verticalLayout.addWidget(self.result)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "qr gen ez"))
        self.setPath.setText(_translate("MainWindow", "..."))
        self.dtnStart.setText(_translate("MainWindow", "сгенерировать"))
